import React, { useEffect } from 'react'

import Head from 'next/head'

import { useDispatch } from 'react-redux'

import { setIsAuthorized } from '@/app/features/formSlice'

import styles from '../styles/modules/Wrapper.module.css'

import Header from '@/components/Header'
import Footer from '@/components/Footer'

const Wrapper = ({ children }) => {
    const dispatch = useDispatch()

    useEffect(() => {
        console.log(JSON.parse(localStorage.getItem('isAuthorized')))
        dispatch(
            setIsAuthorized(JSON.parse(localStorage.getItem('isAuthorized')))
        )
    }, [])

    return (
        <div className={styles.wrapper}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
            </Head>
            <Header />
            <main className={styles.main}>{children}</main>
            <Footer />
        </div>
    )
}

export default Wrapper
